name: Create release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs: {}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Main branch check
        run: |
            echo "Branch: $GITHUB_REF"
            if [$GITHUB_REF != "refs/heads/main"]
            then
              echo "This workflow can only run on the main branch"
              exit 1;
            fi
      - uses: actions/checkout@v3
      - name: Setup git config
        run: |
            git config --global user.email "actions@github.com"
            git config --global user.name "Github Actions"
      - name: Install dependencies
        run: npm install
      # Runs a single command using the runners shell
      - name: Create release
        run: npm run release
      - name: Push new tag to origin
        run: git push --follow-tags origin main
